/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 11 02:14:08 GMT 2022
 */

package org.apache.commons.collections4;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.commons.collections4.FunctorException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class FunctorException_ESTest extends FunctorException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      FunctorException functorException0 = new FunctorException();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      FunctorException functorException0 = new FunctorException((Throwable) null);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      FunctorException functorException0 = new FunctorException("KCZP*30kv]j.~ky");
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      FunctorException functorException0 = new FunctorException("KCZP*30kv]j.~ky", (Throwable) null);
  }
}
